# Generated by Django 2.0.6 on 2018-06-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
